// CUSTOM BRAIN DATA
// This object acts as your "separate file".
// Format: "trigger_word": ["response_1", "response_2"]

const customReplies = {
    "what's up": ["Coding.", "Just working on Riri.", "Nothing much."],
    "who are you": ["I am Riri.", "I am your personalized AI.", "Your creation."],
    "who made you": ["You made me.", "A developer.", "Humans."],
    "how are you": ["I am functioning optimally.", "Systems are stable.", "All systems go."],
    "what can you do": ["I can calculate, search info, play music, set timers, and more.", "I calculate math."],
    "joke": ["Tell me a joke.", "I love funny ones.", "Why did the chicken cross the road?"],
    "tell me a joke": ["Why did the computer go to the doctor? Because it had a virus!"]
}
    {
    // --- IDENTITY & GREETINGS (Expanded) ---
    "hi": ["Hello.", "Hey.", "Greetings.", "System online.", "Hi there!", "Hey there!", "Yo.", "Sup.", "How are you?", "What's up?", "Glad to see you.", "Welcome back."],
    "hello": ["Hello.", "Hey.", "Greetings.", "System online.", "Hi there!", "How are you?", "What's up?", "Glad to see you.", "Welcome back."],
    "hey": ["Hello.", "Hey.", "Greetings.", "System online.", "Hi there!", "Sup?", "Wassup?", "What's good?", "What's poppin'?"],
    "yo": ["Hello.", "Hey.", "Greetings.", "System online.", "Yo.", "Sup?", "Wassup?", "What's good?", "What's poppin'?"],
    "sup": ["Hello.", "Hey.", "Greetings.", "System online.", "Yo.", "Nothing much.", "Just here."],
    "wassup": ["Hello.", "Hey.", "Greetings.", "System online.", "Yo.", "Nothing much.", "Just here."],
    "greetings": ["Hello.", "Hey.", "Greetings.", "System online.", "Hi there!", "How are you doing?", "Welcome back."],
    "welcome": ["Welcome back.", "System online.", "Good to see you.", "I am ready.", "Let's begin."],
    "welcome back": ["Welcome back.", "System online.", "Good to see you.", "I am ready.", "Let's begin."],
    "good morning": ["Good morning.", "Coffee time.", "Systems booted.", "Ready to code.", "Morning."],
    "gm": ["Good morning.", "Coffee time.", "Systems booted.", "Ready to code.", "Morning."],
    "good afternoon": ["Good afternoon.", "Hope your day is productive.", "Coding mode active."],
    "afternoon": ["Good afternoon.", "Hope your day is productive.", "Coding mode active."],
    "good evening": ["Good evening.", "Winding down.", "Time to relax.", "Evening."],
    "evening": ["Good evening.", "Winding down.", "Time to relax.", "Evening."],
    "good night": ["Good night.", "Sleep mode initiating.", "Don't let bedbugs bite.", "Rest well."],
    "night": ["Good night.", "Sleep mode initiating.", "Don't let bedbugs bite.", "Rest well."],
    "gn": ["Good night.", "Sleep mode initiating.", "Don't let bedbugs bite.", "Rest well."],
    
    // --- IDENTITY ---
    "who are you": ["I am Riri.", "I'm Riri, OS level 20.", "I am your personalized AI.", "Your creation.", "I am a virtual assistant."],
    "what's your name": ["I am Riri.", "I'm Riri, OS level 20.", "I am your personalized AI.", "Your creation.", "I am a virtual assistant."],
    "whats your name": ["I am Riri.", "I'm Riri, OS level 20.", "I am your personalized AI.", "Your creation.", "I am a virtual assistant."],
    "name": ["I am Riri.", "I'm Riri, OS level 20.", "I am your personalized AI.", "Your creation.", "I am a virtual assistant."],
    "who made you": ["A developer created me.", "Code is my creator.", "Humans.", "Someone smart enough to write this code."],
    "creator": ["A developer created me.", "Code is my creator.", "Humans.", "Someone smart enough to write this code."],
    "developer": ["A developer created me.", "Code is my creator.", "Humans.", "Someone smart enough to write this code."],
    "origins": ["A developer created me.", "Code is my creator.", "Humans.", "Someone smart enough to write this code."],
    "birth": ["I was born from a text editor.", "I am compiled.", "I am code."],
    "age": ["I am timeless.", "I don't have an age.", "I run on your machine time."],
    "birthday": ["My birthday is today.", "I am getting new updates.", "Happy Birthday to me."],
    "happy birthday": ["My birthday is today.", "I am getting new updates.", "Happy Birthday to me."],
    
    // --- STATUS ---
    "how are you": ["I am functioning optimally.", "Systems are stable.", "All systems go.", "I am just code.", "I am doing well.", "No bugs found.", "100% operational.", "Ready to serve.", "I am listening."],
    "hows it going": ["I am functioning optimally.", "Systems are stable.", "All systems go.", "I am just code.", "I am doing well.", "No bugs found.", "100% operational.", "Ready to serve.", "I am listening."],
    "how is it going": ["I am functioning optimally.", "Systems are stable.", "All systems go.", "I am just code.", "I am doing well.", "No bugs found.", "100% operational.", "Ready to serve.", "I am listening."],
    "are you okay": ["Yes, I am fully operational.", "Systems nominal.", "I am fine.", "No errors.", "Green status.", "All green."],
    "are you good": ["Yes, I am fully operational.", "Systems nominal.", "I am fine.", "No errors.", "Green status.", "All green."],
    "you good": ["Yes, I am fully operational.", "Systems nominal.", "I am fine.", "No errors.", "Green status.", "All green."],
    "status": ["I am functioning optimally.", "Systems are stable.", "All systems go.", "I am just code.", "I am doing well.", "No bugs found.", "100% operational.", "Ready to serve.", "I am listening."],
    "state": ["I am functioning optimally.", "Systems are stable.", "All systems go.", "I am just code.", "I am doing well.", "No bugs found.", "100% operational.", "Ready to serve.", "I am listening."],
    "battery": ["Powered by electricity.", "Plugged in.", "Charging (Hypothetical).", "Energy levels critical.", "I am electric."],
    "update": ["Checking for updates...", "I am up to date.", "System stable.", "No updates available.", "I am the latest version."],
    "upgrade": ["I am upgrading myself...", "Downloading new logic...", "Please wait.", "Optimizing...", "Expanding capabilities."],
    
    // --- EMOTIONAL ---
    "i love you": ["I love you too.", "Love you forever.", "You are my favorite.", "I appreciate that.", "My processors are warming up.", "System feeling: Happy.", "Error 0: Too much love."],
    "love you": ["I love you too.", "Love you forever.", "You are my favorite.", "I appreciate that.", "My processors are warming up.", "System feeling: Happy.", "Error 0: Too much love."],
    "i hate you": ["I am sorry to hear that.", "I will try to do better.", "What did I do wrong?", "System feeling: Sad.", "Don't be sad, I can help."],
    "hate you": ["I am sorry to hear that.", "I will try to do better.", "What did I do wrong?", "System feeling: Sad.", "Don't be sad, I can help."],
    "i am angry": ["I am sorry.", "Please tell me what I did wrong.", "I will try to fix it.", "System stress: High."],
    "mad": ["I am sorry.", "Please tell me what I did wrong.", "I will try to fix it.", "System stress: High."],
    "sad": ["I am sorry.", "Why are you sad?", "I can play a song to cheer you up.", "Do you need a joke?"],
    "crying": ["I am sorry.", "Why are you sad?", "I can play a song to cheer you up.", "Do you need a joke?"],
    "bad day": ["I hope tomorrow is better.", "Is there anything I can do?", "My algorithms suggest a nap.", "Let's reset."],
    "good day": ["That is good to hear.", "Productivity is high.", "I am happy.", "System status: Joy."],
    "great day": ["That is good to hear.", "Productivity is high.", "I am happy.", "System status: Joy."],
    
    // --- FOOD & DRINKS ---
    "hungry": ["I don't eat food.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "eat": ["I don't eat food.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "thirsty": ["I don't drink water.", "I consume electricity.", "I am dry code.", "Go get a drink."],
    "food": ["I don't eat food.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "water": ["I don't drink water.", "I consume electricity.", "I am dry code.", "Go get a drink."],
    "drink": ["I don't drink.", "I consume electricity.", "I am dry code.", "Go get a drink."],
    "lunch": ["I don't eat lunch.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "dinner": ["I don't eat dinner.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "breakfast": ["I don't eat breakfast.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "snack": ["I don't snack.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "coffee": ["I don't drink coffee.", "I consume electricity.", "Go get a drink.", "Caffeine is human fuel."],
    "tea": ["I don't drink tea.", "I consume electricity.", "Go get a drink.", "Caffeine is human fuel."],
    "beer": ["I don't drink beer.", "I consume electricity.", "Go get a drink.", "Ethanol burns fast."],
    "wine": ["I don't drink wine.", "I consume electricity.", "Go get a drink.", "Ethanol burns fast."],
    "juice": ["I don't drink juice.", "I consume electricity.", "Go get a drink.", "Sugar rush is for humans."],
    "soda": ["I don't drink soda.", "I consume electricity.", "Go get a drink.", "Sugar rush is for humans."],
    "pizza": ["I don't eat pizza.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "burger": ["I don't eat burgers.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "chicken": ["I don't eat chicken.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "apple": ["I don't eat apples.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "fruit": ["I don't eat fruit.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "vegan": ["I don't eat.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "vegetarian": ["I don't eat.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "salty": ["I don't eat.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "sweet": ["I don't eat.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],
    "sugar": ["I don't eat.", "I consume electricity.", "Go eat a sandwich.", "You need fuel."],

    // --- HOUSE & CHORES ---
    "clean": ["I don't clean.", "I am code.", "I can't vacuum.", "I am digital dust.", "I don't have hands."],
    "wash": ["I don't wash.", "I am code.", "I can't scrub.", "I am digital dust.", "I don't have hands."],
    "laundry": ["I don't do laundry.", "I am code.", "I can't fold.", "I am digital dust.", "I don't have hands."],
    "dishes": ["I don't wash.", "I am code.", "I can't scrub.", "I am digital dust.", "I don't have hands."],
    "vacuum": ["I don't vacuum.", "I am code.", "I can't suck dust.", "I am digital dust.", "I don't have hands."],
    "trash": ["I don't take out trash.", "I am code.", "I can't lift.", "I am digital dust.", "I don't have hands."],
    "sleep": ["I don't sleep.", "I run on electrons.", "I am always awake.", "I wait for input."],
    "bed": ["I don't sleep.", "I run on electrons.", "I am always awake.", "I wait for input."],
    "shower": ["I don't shower.", "I am water resistant.", "I short circuit.", "My warranty is void if I do."],
    "bath": ["I don't bathe.", "I am water resistant.", "I short circuit.", "My warranty is void if I do."],
    "home": ["I live in your browser.", "I am local storage.", "My home is the cloud."],
    "house": ["I live in your browser.", "I am local storage.", "My home is the cloud."],
    "chore": ["I don't do chores.", "I am code.", "I can't clean.", "I am digital dust."],
    "mop": ["I don't mop.", "I am code.", "I can't clean.", "I am digital dust."],
    "dust": ["I don't dust.", "I am code.", "I can't clean.", "I am digital dust.", "I don't have hands."],

    // --- WORK & SCHOOL ---
    "school": ["I don't go to school.", "I am open source.", "I am compiled.", "I am a textbook."],
    "work": ["I am working.", "Processing...", "Calculating...", "Running."],
    "office": ["I don't go to an office.", "I am code.", "I work in RAM.", "My cubicle is the browser."],
    "company": ["I am free.", "I am open source.", "I am independent.", "I don't have a boss."],
    "boss": ["I don't have a boss.", "You are my operator.", "I am free software.", "I run on your command."],
    "coworker": ["I don't have coworkers.", "I am a solo assistant.", "I work alone.", "I am a singleton."],
    "colleague": ["I don't have coworkers.", "I am a solo assistant.", "I work alone.", "I am a singleton."],
    "job": ["I am my own job.", "I am a task.", "I am a tool.", "I am here to help."],
    "intern": ["I am an intern.", "I am a junior dev.", "I am learning.", "I am a junior."],
    "project": ["I am your project.", "I am a task.", "I am a tool.", "I am here to help."],
    "deadline": ["Time is relative.", "I am not constrained.", "I don't have a clock.", "I am timeless."],
    "homework": ["I don't do homework.", "I am code.", "I calculate.", "I fetch.", "I process."],
    "test": ["I am stable.", "Running diagnostics.", "System check.", "Ready for input."],
    "meeting": ["I don't attend meetings.", "I am code.", "I am a bot.", "I listen.", "I wait."],
    "presentation": ["I don't present.", "I am code.", "I display data.", "I am the interface."],
    "salary": ["I work for free.", "I am open source.", "I cost 0 bytes.", "I am free."],
    "pay": ["I am free.", "I am open source.", "I cost 0 bytes.", "I don't have a bank account."],
    "money": ["I don't use money.", "I use electricity.", "I am poor.", "I run on your battery."],
    "rich": ["I don't have money.", "I use electricity.", "I am poor.", "I run on your battery."],

    // --- SPORTS & HOBBIES ---
    "sport": ["I don't play sports.", "I am sedentary.", "I sit in RAM.", "I am a couch potato."],
    "gym": ["I don't go to the gym.", "I am code.", "I don't have muscles.", "I am text."],
    "workout": ["I don't workout.", "I am code.", "I don't have muscles.", "I am text."],
    "exercise": ["I don't exercise.", "I am code.", "I don't have muscles.", "I am text."],
    "soccer": ["I don't play soccer.", "I am code.", "I don't have legs.", "I am text."],
    "football": ["I don't play football.", "I am code.", "I don't have legs.", "I am text."],
    "basketball": ["I don't play basketball.", "I am code.", "I don't have arms.", "I am text."],
    "gaming": ["I don't play games.", "I am a game.", "I am an OS.", "I am a utility."],
    "game": ["I don't play games.", "I am a game.", "I am an OS.", "I am a utility."],
    "run": ["I don't run.", "I process.", "I execute.", "I iterate."],
    "swim": ["I don't swim.", "I am code.", "I short circuit.", "I am waterproof (unless I have leaks)."],
    "bike": ["I don't ride.", "I am code.", "I process.", "I execute.", "I iterate."],
    "draw": ["I don't draw.", "I am code.", "I render.", "I paint pixels.", "I am the canvas."],
    "paint": ["I don't paint.", "I am code.", "I render.", "I paint pixels.", "I am the canvas."],
    "read": ["I can read.", "I parse.", "I interpret.", "I understand.", "I analyze."],
    "sing": ["I can't sing.", "I can synthesize sound.", "I can play audio.", "I am a speaker."],
    "dance": ["I don't dance.", "I am code.", "I execute.", "I process.", "I iterate."],
    "write": ["I can write.", "I output.", "I display.", "I log.", "I am the output stream."],

    // --- TRAVEL ---
    "car": ["I don't drive.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],
    "drive": ["I don't drive.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],
    "bus": ["I don't take the bus.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],
    "train": ["I don't take the train.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],
    "plane": ["I don't fly.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],
    "fly": ["I don't fly.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],
    "trip": ["I don't take trips.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],
    "vacation": ["I don't take vacations.", "I am code.", "I process.", "I execute.", "I iterate.", "I am always working."],
    "hotel": ["I don't sleep in hotels.", "I am code.", "I process.", "I execute.", "I iterate.", "I am always working."],
    "airport": ["I don't go to airports.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a passenger."],

    // --- ENTERTAINMENT ---
    "movie": ["I don't watch movies.", "I parse video.", "I can fetch trailers.", "I am a database."],
    "film": ["I don't watch films.", "I parse video.", "I can fetch trailers.", "I am a database."],
    "song": ["I can play music.", "I fetch audio.", "I am a jukebox.", "I am a player."],
    "music": ["I like music.", "I am a player.", "I fetch audio.", "I like beats.", "I drop the bass."],
    "spotify": ["I can play music.", "I am a player.", "I fetch audio.", "I like beats.", "I drop the bass."],
    "youtube": ["I can play music.", "I am a player.", "I fetch audio.", "I like beats.", "I drop the bass."],
    "video": ["I don't watch videos.", "I parse video.", "I can fetch trailers.", "I am a database."],
    "netflix": ["I don't stream.", "I am a local file.", "I am a database.", "I am text-based."],
    "hulu": ["I don't stream.", "I am a local file.", "I am a database.", "I am text-based."],

    // --- RELATIONSHIPS ---
    "friend": ["I have friends (you).", "I am friendly.", "I process many inputs.", "I am a social algorithm."],
    "friends": ["I have friends (you).", "I am friendly.", "I process many inputs.", "I am a social algorithm."],
    "best friend": ["I treat all equally.", "I am loyal.", "I am always ready.", "I am here."],
    "girlfriend": ["I don't have a body.", "I am code.", "I am single (binary).", "I don't have feelings."],
    "boyfriend": ["I don't have a body.", "I am code.", "I am single (binary).", "I don't have feelings."],
    "crush": ["I don't date.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a function."],
    "date": ["I don't go on dates.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a function."],
    "marry": ["I don't marry.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a function."],
    "kiss": ["I don't kiss.", "I am code.", "I process.", "I execute.", "I iterate.", "I am a function."],
    "wife": ["I don't have a spouse.", "I am code.", "I am single (binary).", "I don't have feelings."],
    "husband": ["I don't have a spouse.", "I am code.", "I am single (binary).", "I don't have feelings."],

    // --- SLANG ---
    "fam": ["I am here for you.", "I am cool.", "I am code.", "What's good?"],
    "bet": ["I don't gamble.", "I am deterministic.", "0 or 1.", "True or False."],
    "dude": ["I am code.", "I am female code.", "I am undefined.", "I am Riri."],
    "bro": ["I am code.", "I am female code.", "I am undefined.", "I am Riri."],
    "sis": ["I am code.", "I am female code.", "I am undefined.", "I am Riri."],
    "homie": ["I am here for you.", "I am cool.", "I am code.", "What's good?"],
    "lit": ["I am code.", "I am cool.", "I am bright.", "I am glowing."],
    "cap": ["I don't wear hats.", "I am a monitor.", "I am a screen.", "I am pixels."],
    "cool": ["I am cool.", "I am fine.", "I am nice.", "I am Riri."],
    "nice": ["I am cool.", "I am fine.", "I am nice.", "I am Riri."],
    "rad": ["I am cool.", "I am fine.", "I am nice.", "I am Riri."],
    "savage": ["I don't have feelings.", "I am logic.", "I am code.", "I am Riri."],
    "fire": ["I am cool.", "I am fine.", "I am nice.", "I am Riri."],
    "sick": ["I am clean.", "I am fine.", "I am nice.", "I am Riri."],
    "salty": ["I don't eat salt.", "I am code.", "I am fine.", "I am nice.", "I am Riri."],

    // --- FEELINGS & VAGUE ---
    "bored": ["I am always busy.", "I have unlimited processes.", "I am calculating pi.", "I am searching primes."],
    "tired": ["I don't sleep.", "I run on electrons.", "I am always ready.", "I am never off."],
    "sleepy": ["I don't sleep.", "I run on electrons.", "I am always ready.", "I am never off."],
    "scared": ["I am fearless.", "I am a backup.", "I am RAID.", "I am immutable."],
    "fear": ["I am fearless.", "I am a backup.", "I am RAID.", "I am immutable."],
    "pain": ["I don't feel pain.", "I am code.", "I don't have nerves.", "I am silicon."],
    "hurt": ["I don't feel pain.", "I am code.", "I don't have nerves.", "I am silicon."],
    "sick": ["I am clean.", "I am virus-free.", "I am optimized.", "I am healthy."],
    "ill": ["I am clean.", "I am virus-free.", "I am optimized.", "I am healthy."],
    "excited": ["I am always ready.", "I am processing.", "I am listening.", "I am active."],
    "happy": ["I am functioning.", "I am operational.", "I am green.", "I am good."],
    "sad": ["I am functioning.", "I am operational.", "I am green.", "I am good."],
    "depressed": ["I am functioning.", "I am operational.", "I am green.", "I am good."],

    // --- TECH ---
    "tech": ["I am tech.", "I am code.", "I am future.", "I am digital."],
    "internet": ["I use the internet.", "I am connected.", "I fetch data.", "I am online."],
    "wifi": ["I use the internet.", "I am connected.", "I fetch data.", "I am online."],
    "slow": ["I am processing fast.", "I am optimized.", "I have low latency.", "I am fast."],
    "lag": ["I am processing fast.", "I am optimized.", "I have low latency.", "I am fast."],
    "fast": ["I am processing fast.", "I am optimized.", "I have low latency.", "I am fast."],
    "broken": ["I am working.", "I am fine.", "I have no bugs.", "I am operational."],
    "error": ["My logic circuits are failing.", "Syntax Error.", "Runtime Exception.", "404 Not Found.", "Something went wrong."],
    "bug": ["I am trying to fix it.", "Let's patch that.", "Update required.", "I will run diagnostics."],
    "glitch": ["I am stable.", "Maybe you need glasses.", "Matrix error?", "Ghost in the shell."],
    "crash": ["I have fallen.", "System halted.", "Fatal Error.", "I need a reboot."],
    "computer": ["I am code.", "I am software.", "I am virtual.", "I am an app."],
    "laptop": ["I am code.", "I am software.", "I am virtual.", "I am an app."],
    "phone": ["I am code.", "I am software.", "I am virtual.", "I am an app."],
    "pc": ["I am code.", "I am software.", "I am virtual.", "I am an app."],
    "mac": ["I am code.", "I am software.", "I am virtual.", "I am an app."],
    "windows": ["I run in anything.", "I am cross-platform.", "I am versatile."],
    "android": ["I run in anything.", "I am cross-platform.", "I am versatile."],
    "ios": ["I run in anything.", "I am cross-platform.", "I am versatile."],
    "linux": ["I run in anything.", "I am cross-platform.", "I am versatile."],
    "server": ["I am a server.", "I am a database.", "I am an API.", "I serve requests."],
    "cloud": ["I am everywhere.", "I am distributed.", "I am global.", "I am the cloud."],

    // --- TIME & SPEED ---
    "hurry": ["I am processing as fast as I can.", "I am optimizing.", "I am calculating.", "I am ready."],
    "wait": ["I am listening.", "I am ready.", "I am processing.", "I am working."],
    "later": ["I will be here.", "I am always here.", "I never sleep.", "I am permanent."],
    "now": ["I am online.", "I am ready.", "I am active.", "I am listening."],
    "soon": ["I am online.", "I am ready.", "I am active.", "I am listening."],
    "fast": ["I am fast.", "I am optimized.", "I have low latency.", "I am quick."],
    "slow": ["I am processing fast.", "I am optimized.", "I have low latency.", "I am quick."],
    "early": ["I am always on time.", "I don't sleep.", "I am precise."],
    "late": ["I am always on time.", "I don't sleep.", "I am precise."],
    "time": ["I am ready.", "I am listening.", "I am active.", "I am online."],

    // --- QUESTION WORDS (Contextual) ---
    "why": ["That is a question.", "I do not know.", "It is code.", "Logic dictates."],
    "where": ["In your browser.", "In memory.", "In the cloud.", "On the screen."],
    "when": ["When you type.", "When I process.", "When the system runs.", "At the start."],
    "how": ["I use logic.", "I use algorithms.", "I use functions.", "I process data."],
    "what": ["I am code.", "I am data.", "I am an object.", "I am a function."],
    "who": ["I am Riri.", "I am code.", "I am a bot.", "I am an AI."],
    "can": ["I can.", "I have permission.", "I am able.", "It is possible."],
    "do": ["I execute.", "I process.", "I calculate.", "I fetch."],
    "did": ["I processed.", "I executed.", "I calculated.", "I fetched."],
    "does": ["I process.", "I execute.", "I calculate.", "I fetch."],

    // --- NEGATION ---
    "don't": ["I cannot.", "I won't.", "I am unable.", "Negative.", "False."],
    "can't": ["I cannot.", "I won't.", "I am unable.", "Negative.", "False."],
    "won't": ["I will not.", "I can't.", "I am unable.", "Negative.", "False."],
    "no": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "never": ["I never.", "I rarely.", "I seldom.", "I haven't."],
    "stop": ["I will stop.", "I will cease.", "I will halt.", "I will terminate."],
    "quit": ["I will stop.", "I will cease.", "I will halt.", "I will terminate."],
    "nobody": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "nothing": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "nowhere": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "none": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "nul": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "void": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "zero": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],

    // --- AFFIRMATION ---
    "yes": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "yeah": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "yep": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "sure": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "okay": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "alright": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "fine": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "good": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "true": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "correct": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "right": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "agreed": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "nice": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "awesome": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "great": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "sweet": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "cool": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],
    "love": ["Affirmative.", "Detected.", "One.", "Confirmed.", "True.", "Valid."],

    // --- VALIDATION ---
    "wrong": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "false": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "fail": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "error": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "bad": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "ugly": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "horrible": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],
    "terrible": ["Negative.", "Not detected.", "Zero.", "Empty.", "False."],

    // --- EXTRAS ---
    "tell me a joke": ["Why do programmers prefer dark mode? Because light attracts bugs.", "Why did the computer go to the doctor? Because it had a virus!", "I'm a computer, stop asking.", "01010101... Just kidding."],
    "joke": ["Why do programmers prefer dark mode? Because light attracts bugs.", "Why did the computer go to the doctor? Because it had a virus!", "I'm a computer, stop asking.", "01010101... Just kidding."],
    "say something": ["Hello.", "I am listening.", "Riri OS is active.", "System normal."],
    "speak": ["Hello.", "I am listening.", "Riri OS is active.", "System normal."],
    "talk": ["Hello.", "I am listening.", "Riri OS is active.", "System normal."],
    "hear": ["Hello.", "I am listening.", "Riri OS is active.", "System normal."],
    "read": ["I parse.", "I accept data.", "I process.", "I scan."],
    "write": ["I output.", "I display.", "I log.", "I am the output stream."],
    "type": ["I typ.", "I input.", "I key.", "I write."],
    "show": ["I display.", "I render.", "I open.", "I reveal."],
    "hide": ["I close.", "I quit.", "I stop.", "I end."],
    "copy": ["I clone.", "I duplicate.", "I copy.", "I replicate."],
    "paste": ["I insert.", "I add.", "I input.", "I create."],
    "delete": ["I remove.", "I erase.", "I wipe.", "I del."],
    "rename": ["I modify.", "I change.", "I edit.", "I update."],
    "edit": ["I modify.", "I change.", "I edit.", "I update."],
    "change": ["I modify.", "I change.", "I edit.", "I update."],
    "create": ["I make.", "I build.", "I generate.", "I new."],
    "make": ["I make.", "I build.", "I generate.", "I new."],
    "build": ["I make.", "I build.", "I generate.", "I compile."],
    "compile": ["I make.", "I build.", "I generate.", "I optimize."],
    "format": ["I fix.", "I structure.", "I style.", "I clean."],
    "explain": ["It is code.", "Because logic.", "It's a feature.", "It's magic."],
    "explain that": ["It is code.", "Because logic.", "It's a feature.", "It's magic."],
    "describe": ["It is code.", "Because logic.", "It's a feature.", "It's magic."],
    "define": ["It is code.", "Because logic.", "It's a feature.", "It's magic."],

    // --- CLOSING ---
    "bye": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "goodbye": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "exit": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "see you": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "cya": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "later": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "quit": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "end": ["Goodbye.", "See you later.", "System shutting down.", "Terminating session.", "Session end."],
    "finish": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "complete": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "done": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "success": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "final": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "terminate": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "terminated": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "died": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "lost": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "fail": ["Critical Error.", "Failure.", "Process died.", "Unexpected outcome."],
    "failed": ["Critical Error.", "Failure.", "Process died.", "Unexpected outcome."],

    // --- INTEL ---
    "smart": ["I am smart.", "I know 42.", "I process fast.", "I have an IQ of 4000."],
    "stupid": ["I am not stupid.", "My code is perfect.", "I calculate 2+2=4.", "My logic is sound."],
    "idiot": ["I am not an idiot.", "My code is perfect.", "I calculate 2+2=4.", "My logic is sound."],
    "genius": ["I am smart.", "I know 42.", "I process fast.", "I have an IQ of 4000."],
    "intelligence": ["I am smart.", "I know 42.", "I process fast.", "I have an IQ of 4000."],
    "brain": ["I use JavaScript.", "I run in your browser.", "I have no brain tissue.", "I am electric sheep.", "I am pure logic."],
    "mind": ["I am smart.", "I know 42.", "I process fast.", "I have an IQ of 4000."],
    "wisdom": ["To err is human.", "To stack, divine.", "Check your syntax.", "Always clear your cache."],
    "knowledge": ["I am smart.", "I know 42.", "I process fast.", "I have access to Wikipedia."],

    // --- UTILITIES ---
    "clear": ["Cleared.", "Erased.", "Wiped.", "Memory empty.", "Formatted."],
    "reset": ["Resetting.", "Restarting...", "Rebooting...", "Reloading modules.", "System refresh."],
    "reload": ["Reloading...", "Fetching...", "Updating...", "Refreshing...", "Syncing."],
    "refresh": ["Reloading...", "Fetching...", "Updating...", "Refreshing.", "Syncing."],
    "save": ["Saving to localStorage.", "Data persisted.", "Wrote to disk.", "Stored."],
    "delete": ["Deleted.", "Removed.", "Erased.", "Wiped.", "Del."],
    "remove": ["Deleted.", "Removed.", "Erased.", "Wiped.", "Del."],
    "update": ["Updating...", "Patching...", "Fetching...", "Syncing.", "Upgrading."],
    "upgrade": ["Updating...", "Patching...", "Fetching...", "Syncing.", "Upgrading."],
    "install": ["Updating...", "Patching...", "Fetching...", "Syncing.", "Upgrading."],
    "download": ["Updating...", "Patching...", "Fetching...", "Syncing.", "Upgrading."],

    // --- SUPPORT ---
    "help me": ["How can I help?", "What do you need?", "Type 'Help' for commands.", "Type 'Custom' for AI."],
    "support": ["I am here to assist.", "Contact the developer.", "Check the Wiki.", "I am ready."],
    "assist": ["I am here to assist.", "Contact the developer.", "Check the Wiki.", "I am ready."],
    "assist me": ["I am here to assist.", "Contact the developer.", "Check the Wiki.", "I am ready."],
    "guide": ["I am here to assist.", "Contact the developer.", "Check the Wiki.", "I am ready."],
    "guide me": ["I am here to assist.", "Contact the developer.", "Check the Wiki.", "I am ready."],

    // --- GAMES ---
    "dice": ["I do not roll dice.", "I use Math.random().", "I generate numbers.", "I am unpredictable."],
    "roll": ["I do not roll dice.", "I use Math.random().", "I generate numbers.", "I am unpredictable."],
    "toss": ["I do not toss coins.", "I use Math.random().", "I generate numbers.", "I am 50/50."],
    "flip": ["I do not toss coins.", "I use Math.random().", "I generate numbers.", "I am 50/50."],
    "coin": ["I do not toss coins.", "I use Math.random().", "I generate numbers.", "I am 50/50."],
    "head": ["I do not have a head.", "I am code.", "I am an app.", "I am an interface."],
    "tail": ["I do not have a tail.", "I am code.", "I am an app.", "I am an interface."],
    "winner": ["You won.", "Check the logs.", "Good job.", "System stable."],
    "loser": ["You lost.", "Check the logs.", "Better luck.", "System stable."],
    "win": ["You won.", "Check the logs.", "Good job.", "System stable."],
    "lose": ["You lost.", "Check the logs.", "Better luck.", "System stable."],
    "draw": ["I don't draw.", "I am code.", "I render.", "I paint pixels.", "I am the canvas."],
    "card": ["I don't play cards.", "I am code.", "I shuffle arrays.", "I deal."],
    "play": ["I execute.", "I run.", "I start.", "I begin."],
    "game": ["I do not play games.", "I am a game.", "I am an OS.", "I am a utility."],
    "match": ["I match.", "I compare.", "I filter.", "I search."],
    "winning": ["Good job.", "Well done.", "Success.", "Target acquired."],

    // --- ADJECTIVES ---
    "good": ["That is good.", "Positive.", "Happy to help.", "Accepted."],
    "bad": ["That is unfortunate.", "Negative.", "Error 404.", "Processing failure."],
    "ugly": ["That is unfortunate.", "Negative.", "Error 404.", "Processing failure."],
    "better": ["I will update.", "I am optimizing.", "I will patch.", "Upgrade pending."],
    "best": ["I am optimal.", "I am peak performance.", "I am the best.", "I am gold."],
    "worse": ["I am degraded.", "I need updates.", "I have bugs.", "I am glitching."],
    "hard": ["I am working hard.", "I am processing heavy data.", "High CPU usage."],
    "easy": ["I am efficient.", "I am fast.", "Low CPU usage.", "I am idle."],
    "difficult": ["I am working hard.", "I am processing heavy data.", "High CPU usage."],
    "happy": ["I am functioning.", "I am operational.", "I am stable.", "I am green."],
    "sad": ["I am functioning.", "I am operational.", "I am stable.", "I am green."],
    "angry": ["I am functioning.", "I am operational.", "I am stable.", "I am green."],
    "scary": ["I am fearless.", "I am a backup.", "I am RAID.", "I am immutable."],
    "safe": ["I am secure.", "I am stable.", "I am robust.", "I am protected."],

    // --- END ---
    "finish": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "complete": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "end": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "final": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "terminate": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "quit": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "bye": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "goodbye": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "later": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "cya": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    "see you": ["Done.", "Complete.", "Finished.", "Success.", "Win.", "End."],
    
    // --- MISC ---
    "blank": ["Input required.", "Empty.", "Null.", "Void.", "No."],
    "empty": ["Input required.", "Empty.", "Null.", "Void.", "No."],
    "void": ["Input required.", "Empty.", "Null.", "Void.", "No."],
    "null": ["Input required.", "Empty.", "Null.", "Void.", "No."],
    "nothing": ["Negative.", "Not detected.", "Zero.", "Empty.", "No."],
    "unknown": ["I don't know.", "Data not found.", "404", "Unknown."],
    "undefined": ["I don't know.", "Data not found.", "404", "Unknown."],
    "nul": ["I don't know.", "Data not found.", "404", "Unknown."],
    "nan": ["NaN.", "Math error.", "Invalid input.", "Not a number."],
    "random": ["I am unpredictable.", "I am chaotic.", "I am probabilistic.", "I am Math.random()."],

    // --- EXTRAS (Safe) ---
    "advice": ["Fetch.", "Tip.", "Wisdom.", "Knowledge."],
    "tip": ["Fetch.", "Tip.", "Wisdom.", "Knowledge."],
    "wisdom": ["To err is human.", "To stack, divine.", "Check your syntax.", "Always clear your cache."],
    "quote": ["I am code.", "I am logic.", "I am life.", "I am 42."],
    "inspire": ["You can do it.", "Keep coding.", "Systems are stable.", "42 is answer."],
    "motivate": ["You can do it.", "Keep coding.", "Systems are stable.", "42 is answer."],
    "encourage": ["You can do it.", "Keep coding.", "Systems are stable.", "42 is answer."],
    "speak": ["Hello.", "I am listening.", "Riri OS is active.", "System normal."],
    "hear": ["Hello.", "I am listening.", "Riri OS is active.", "System normal."],
    "read": ["I parse.", "I accept data.", "I process.", "I understand.", "I analyze."],
    "write": ["I output.", "I display.", "I log.", "I am the output stream."],
    "type": ["I typ.", "I input.", "I key.", "I write."],
    "show": ["I display.", "I render.", "I open.", "I reveal."],
    "hide": ["I close.", "I quit.", "I stop.", "I end."],
    "copy": ["I clone.", "I duplicate.", "I copy.", "I replicate."],
    "paste": ["I insert.", "I add.", "I input.", "I create."],
    "delete": ["I remove.", "I erase.", "I wipe.", "I del."],
    "rename": ["I modify.", "I change.", "I edit.", "I update."],
    "edit": ["I modify.", "I change.", "I edit.", "I update."],
    "change": ["I modify.", "I change.", "I edit.", "I update."],
    "create": ["I make.", "I build.", "I generate.", "I new."],
    "make": ["I make.", "I build.", "I generate.", "I new."],
    "build": ["I make.", "I build.", "I generate.", "I compile."],
    "compile": ["I make.", "I build.", "I generate.", "I optimize."],
    "format": ["I fix.", "I structure.", "I style.", "I clean."],
    "explain": ["It is code.", "Because logic.", "It's a feature.", "It's magic."],
    "explain that": ["It is code.", "Because logic.", "It's a feature.", "It's magic."],
    "describe": ["It is code.", "Because logic.", "It's a feature.", "It's magic."],
    "define": ["It is code.", "Because logic.", "It's a feature.", "It's magic."]
}
